1. 행과 열의 선택

In [1]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)
iris[1:4]

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [2]:
iris['sepal length (cm)'].head(4)

0    5.1
1    4.9
2    4.7
3    4.6
Name: sepal length (cm), dtype: float64

In [3]:
iris[['sepal length (cm)', 'sepal width (cm)']].head(4)

   sepal length (cm)  sepal width (cm)
0                5.1               3.5
1                4.9               3.0
2                4.7               3.2
3                4.6               3.1

In [4]:
iris.iloc[1:4]

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [5]:
iris.iloc[[1, 3, 5], 2:4]

   petal length (cm)  petal width (cm)
1                1.4               0.2
3                1.5               0.2
5                1.7               0.4

In [6]:
iris.iloc[:, [True, True, False, True]]

     sepal length (cm)  sepal width (cm)  petal width (cm)
0                  5.1               3.5               0.2
1                  4.9               3.0               0.2
2                  4.7               3.2               0.2
3                  4.6               3.1               0.2
4                  5.0               3.6               0.2
..                 ...               ...               ...
145                6.7               3.0               2.3
146                6.3               2.5               1.9
147                6.5               3.0               2.0
148                6.2               3.4               2.3
149                5.9               3.0               1.8

[150 rows x 3 columns]

In [7]:
iris.loc[1:3]

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [8]:
iris.loc[[1,2], 'sepal length (cm)':'petal length (cm)']

   sepal length (cm)  sepal width (cm)  petal length (cm)
1                4.9               3.0                1.4
2                4.7               3.2                1.3

In [9]:
score = pd.DataFrame(
    {'국어': [100, 80], '수학': [75, 90], '영어': [90, 95]},
    index=['장화', '홍련']
)
score.loc['홍련', '영어'] = 100
score['국어'] = score['국어'] - 5
score

    국어  수학   영어
장화  95  75   90
홍련  75  90  100

In [10]:
new_students = pd.DataFrame(
    {'국어': [70, 85],'수학': [65, 100],'영어': [95, 65]},
    index=['콩쥐', '팥쥐']
)
score = pd.concat([score, new_students])

new_student = pd.Series(
    {'국어': 85, '수학': 55, '영어': 95},
    name='해님'
)
score = pd.concat([score, new_student.to_frame().T])
score

    국어   수학   영어
장화  95   75   90
홍련  75   90  100
콩쥐  70   65   95
팥쥐  85  100   65
해님  85   55   95

In [11]:
new_student2 = {'국어': 75, '수학': 80, '영어': 80}
pd.concat([score, pd.DataFrame([new_student2])], ignore_index=True)

   국어   수학   영어
0  95   75   90
1  75   90  100
2  70   65   95
3  85  100   65
4  85   55   95
5  75   80   80

In [12]:
science = [80, 70, 90, 85, 75]
score['과학'] = science
score['학년'] = 1
score

    국어   수학   영어  과학  학년
장화  95   75   90  80   1
홍련  75   90  100  70   1
콩쥐  70   65   95  90   1
팥쥐  85  100   65  85   1
해님  85   55   95  75   1

In [13]:
score['과학'] = score['과학'] + 5
score['총점'] = score['국어'] + score['수학'] + score['영어'] + score['과학']
score

    국어   수학   영어  과학  학년   총점
장화  95   75   90  85   1  345
홍련  75   90  100  75   1  340
콩쥐  70   65   95  95   1  325
팥쥐  85  100   65  90   1  340
해님  85   55   95  80   1  315

In [14]:
score.drop('장화', inplace=True)
score.drop(columns=['과학', '학년', '총점'], inplace=True)
score

    국어   수학   영어
홍련  75   90  100
콩쥐  70   65   95
팥쥐  85  100   65
해님  85   55   95

2. 조건식을 이용한 데이터 필터링

In [15]:
import pandas as pd
students = pd.DataFrame({
    '이름': ['장화', '홍련', '콩쥐', '팥쥐', '해님', '달님'],
    '국어': [70, 85, None, 100, None, 85],
    '수학': [65, 100, 80, 95, None, 70]
})
students[students['이름'] == '장화']

   이름    국어    수학
0  장화  70.0  65.0

In [16]:
students[(students['국어'] >= 80) & (students['수학'] >= 80)]

   이름     국어     수학
1  홍련   85.0  100.0
3  팥쥐  100.0   95.0

In [17]:
students.loc[6, '이름':'수학'] = ['별님', 50, 60]
students.loc[
    (students['국어'] >= 80) & (students['수학'] >= 70),
    '합격'
] = 'Pass'
students.loc[students['합격'] != 'Pass', '합격'] = 'Fail'
students

   이름     국어     수학    합격
0  장화   70.0   65.0  Fail
1  홍련   85.0  100.0  Pass
2  콩쥐    NaN   80.0  Fail
3  팥쥐  100.0   95.0  Pass
4  해님    NaN    NaN  Fail
5  달님   85.0   70.0  Pass
6  별님   50.0   60.0  Fail

In [18]:
import numpy as np
condition_list = [
    students['국어'] >= 90,
    (students['국어'] >= 80) & (students['국어'] < 90),
    (students['국어'] >= 70) & (students['국어'] < 80)
]
choice_list = ['A', 'B', 'C']
students['점수'] = np.select(condition_list, choice_list, default='F')
students

   이름     국어     수학    합격 점수
0  장화   70.0   65.0  Fail  C
1  홍련   85.0  100.0  Pass  B
2  콩쥐    NaN   80.0  Fail  F
3  팥쥐  100.0   95.0  Pass  A
4  해님    NaN    NaN  Fail  F
5  달님   85.0   70.0  Pass  B
6  별님   50.0   60.0  Fail  F

In [19]:
students.isna().sum() # 열 기준

이름    0
국어    2
수학    1
합격    0
점수    0
dtype: int64

In [20]:
students.isna().sum(axis=1)   # 행 기준

0    0
1    0
2    1
3    0
4    2
5    0
6    0
dtype: int64

In [21]:
students.dropna()          # 결측값이 포함된 모든 행 삭제

   이름     국어     수학    합격 점수
0  장화   70.0   65.0  Fail  C
1  홍련   85.0  100.0  Pass  B
3  팥쥐  100.0   95.0  Pass  A
5  달님   85.0   70.0  Pass  B
6  별님   50.0   60.0  Fail  F

In [22]:
students.dropna(thresh=4) # 결측값이 아닌 값이 4개 이상인 행만 유지

   이름     국어     수학    합격 점수
0  장화   70.0   65.0  Fail  C
1  홍련   85.0  100.0  Pass  B
2  콩쥐    NaN   80.0  Fail  F
3  팥쥐  100.0   95.0  Pass  A
5  달님   85.0   70.0  Pass  B
6  별님   50.0   60.0  Fail  F

In [23]:
health = pd.DataFrame({
    '연도': [2017, 2018, 2019, 2020, 2021, 2022],
    '키': [160, 162, 165, None, None, 166],
    '몸무게': [53, 52, None, 50, 51, 54],
    '시력': [1.2, None, 1.2, 1.2, 1.1, 0.8],
    '병결': [None, None, None, 2, None, 1]
})

In [24]:
health.fillna(0)

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  0.0
1  2018  162.0  52.0  0.0  0.0
2  2019  165.0   0.0  1.2  0.0
3  2020    0.0  50.0  1.2  2.0
4  2021    0.0  51.0  1.1  0.0
5  2022  166.0  54.0  0.8  1.0

In [25]:
health.fillna(health.mean())

     연도       키   몸무게   시력   병결
0  2017  160.00  53.0  1.2  1.5
1  2018  162.00  52.0  1.1  1.5
2  2019  165.00  52.0  1.2  1.5
3  2020  163.25  50.0  1.2  2.0
4  2021  163.25  51.0  1.1  1.5
5  2022  166.00  54.0  0.8  1.0

In [26]:
# 직전 값으로 대체
health.ffill()

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  NaN
1  2018  162.0  52.0  1.2  NaN
2  2019  165.0  52.0  1.2  NaN
3  2020  165.0  50.0  1.2  2.0
4  2021  165.0  51.0  1.1  2.0
5  2022  166.0  54.0  0.8  1.0

In [27]:
# 이후 값으로 대체
health.bfill()

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  2.0
1  2018  162.0  52.0  1.2  2.0
2  2019  165.0  50.0  1.2  2.0
3  2020  166.0  50.0  1.2  2.0
4  2021  166.0  51.0  1.1  1.0
5  2022  166.0  54.0  0.8  1.0

In [28]:
health['키'].drop_duplicates()

0    160.0
1    162.0
2    165.0
3      NaN
5    166.0
Name: 키, dtype: float64

In [29]:
health[['시력', '병결']].drop_duplicates()

    시력   병결
0  1.2  NaN
1  NaN  NaN
3  1.2  2.0
4  1.1  NaN
5  0.8  1.0

4. 정렬

In [30]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)
iris.sort_index(ascending=False, inplace=True)
iris.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
149                5.9               3.0                5.1               1.8
148                6.2               3.4                5.4               2.3
147                6.5               3.0                5.2               2.0
146                6.3               2.5                5.0               1.9
145                6.7               3.0                5.2               2.3

In [31]:
iris.sort_index(axis=1, ascending=True, inplace=True)
iris.head()

     petal length (cm)  petal width (cm)  sepal length (cm)  sepal width (cm)
149                5.1               1.8                5.9               3.0
148                5.4               2.3                6.2               3.4
147                5.2               2.0                6.5               3.0
146                5.0               1.9                6.3               2.5
145                5.2               2.3                6.7               3.0

In [32]:
iris.sort_values('petal length (cm)')
iris

     petal length (cm)  petal width (cm)  sepal length (cm)  sepal width (cm)
149                5.1               1.8                5.9               3.0
148                5.4               2.3                6.2               3.4
147                5.2               2.0                6.5               3.0
146                5.0               1.9                6.3               2.5
145                5.2               2.3                6.7               3.0
..                 ...               ...                ...               ...
4                  1.4               0.2                5.0               3.6
3                  1.5               0.2                4.6               3.1
2                  1.3               0.2                4.7               3.2
1                  1.4               0.2                4.9               3.0
0                  1.4               0.2                5.1               3.5

[150 rows x 4 columns]

In [33]:
iris.sort_values(['petal width (cm)', 'sepal length (cm)'])

     petal length (cm)  petal width (cm)  sepal length (cm)  sepal width (cm)
13                 1.1               0.1                4.3               3.0
12                 1.4               0.1                4.8               3.0
37                 1.4               0.1                4.9               3.6
9                  1.5               0.1                4.9               3.1
32                 1.5               0.1                5.2               4.1
..                 ...               ...                ...               ...
136                5.6               2.4                6.3               3.4
140                5.6               2.4                6.7               3.1
100                6.0               2.5                6.3               3.3
144                5.7               2.5                6.7               3.3
109                6.1               2.5                7.2               3.6

[150 rows x 4 columns]