<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import pandas as pd

HR1 = pd.DataFrame({
    '이름': ['장화', '홍련'],
    '부서': ['영업', '회계'],
    '직급': ['팀장', '사원']
})
HR2 = pd.DataFrame({
    '이름': ['콩쥐', '팥쥐'],
    '직급': ['사원', '팀장'],
    '부서': ['영업', '인사']
})
pd.concat([HR1, HR2], axis=0)

   이름  부서  직급
0  장화  영업  팀장
1  홍련  회계  사원
0  콩쥐  영업  사원
1  팥쥐  인사  팀장

In [2]:
HR3 = pd.DataFrame({
    '이름': ['콩쥐', '팥쥐'],
    '부서': ['영업', '인사'],
    '급여': [3500, 2800]
})
pd.concat([HR1, HR3], axis=0, ignore_index=True)

   이름  부서   직급      급여
0  장화  영업   팀장     NaN
1  홍련  회계   사원     NaN
2  콩쥐  영업  NaN  3500.0
3  팥쥐  인사  NaN  2800.0

In [3]:
HR4 = pd.Series({1: 2500}, name='급여')
pd.concat([HR1, HR4], axis=1)

   이름  부서  직급      급여
0  장화  영업  팀장     NaN
1  홍련  회계  사원  2500.0

In [4]:
HR5 = pd.DataFrame({'급여': [4500, 3000, 3500]})
pd.concat([HR1, HR5], axis=1)

    이름   부서   직급    급여
0   장화   영업   팀장  4500
1   홍련   회계   사원  3000
2  NaN  NaN  NaN  3500

In [5]:
product = pd.DataFrame({
    '상품코드': ['G1', 'G2', 'G3', 'G4'],
    '상품명': ['우유', '감자', '빵', '치킨']
})
sale = pd.DataFrame({
    '주문번호': [1001, 1002, 1002, 1003, 1004],
    '상품코드': ['G4', 'G3', 'G1', 'G3', 'G5'],
    '주문수량': [1, 4, 2, 2, 3]
})
sale.merge(product, on='상품코드', how='inner')

   주문번호 상품코드  주문수량 상품명
0  1001   G4     1  치킨
1  1002   G3     4   빵
2  1003   G3     2   빵
3  1002   G1     2  우유

In [6]:
sale.merge(product, on='상품코드', how='outer', sort=True)

     주문번호 상품코드  주문수량  상품명
0  1002.0   G1   2.0   우유
1     NaN   G2   NaN   감자
2  1002.0   G3   4.0    빵
3  1003.0   G3   2.0    빵
4  1001.0   G4   1.0   치킨
5  1004.0   G5   3.0  NaN

In [7]:
sale.merge(product, left_on='상품코드', right_on='상품코드', how='left')

   주문번호 상품코드  주문수량  상품명
0  1001   G4     1   치킨
1  1002   G3     4    빵
2  1002   G1     2   우유
3  1003   G3     2    빵
4  1004   G5     3  NaN

In [8]:
sale_merged = sale.merge(product, on='상품코드', how='outer', sort=True)
sale_merged.shape

(6, 4)

In [9]:
import pandas as pd
from sklearn.datasets import load_iris

IRIS = load_iris()
iris = pd.DataFrame(IRIS.data, columns=IRIS.feature_names)
iris['class'] = IRIS.target
iris['class'] = iris['class'].map({
    0: 'setosa', 1: 'versicolor', 2: 'virginica'
})
iris.groupby(by='class').mean()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
class,,,,
setosa,5.006,3.428,1.462,0.246
versicolor,5.936,2.770,4.260,1.326
virginica,6.588,2.974,5.552,2.026

In [10]:
iris.groupby(by='class').median()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
class,,,,
setosa,5.0,3.4,1.50,0.2
versicolor,5.9,2.8,4.35,1.3
virginica,6.5,3.0,5.55,2.0

In [11]:
pd.Series(iris['class']).value_counts()

virginica     50
versicolor    50
setosa        50
Name: class, dtype: int64

In [12]:
iris['petal width level'] = pd.qcut(
    iris['petal width (cm)'], q=3, labels=['short', 'middle', 'long']
)
pd.Series(iris['petal width level']).value_counts().to_frame()

        petal width level
middle                 52
short                  50
long                   48

In [13]:
pd.crosstab(iris['petal width level'], iris['class'])

class              setosa  versicolor  virginica
petal width level
short                  50           0          0
middle                  0          48          4
long                    0           2         46

In [14]:
import pandas as pd

score = {
    '학년': [1, 1, 1, 1, 2, 2],
    '반': ['A', 'A', 'B', 'B', 'C', 'C'],
    '성별': ['여자', '남자', '여자', '남자', '여자', '남자'],
    '성적': [76, 88, 85, 72, 68, 70]
}

score = pd.DataFrame(score)
score

   학년  반  성별  성적
0   1  A  여자  76
1   1  A  남자  88
2   1  B  여자  85
3   1  B  남자  72
4   2  C  여자  68
5   2  C  남자  70

In [15]:
score = score.pivot_table(
    index=['학년', '반'], columns='성별', values='성적'
)
score

성별    남자  여자
학년 반
1  A  88  76
   B  72  85
2  C  70  68

In [16]:
score.reset_index().melt(
    id_vars=['학년', '반'], var_name='성별', value_name='성적'
)

   학년  반  성별  성적
0   1  A  남자  88
1   1  B  남자  72
2   2  C  남자  70
3   1  A  여자  76
4   1  B  여자  85
5   2  C  여자  68