<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#제4절-함수-적용과-특수-데이터-처리" data-toc-modified-id="제4절-함수-적용과-특수-데이터-처리-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>제4절 함수 적용과 특수 데이터 처리</a></span><ul class="toc-item"><li><span><a href="#2.-문자열-데이터-처리" data-toc-modified-id="2.-문자열-데이터-처리-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>2. 문자열 데이터 처리</a></span></li><li><span><a href="#3.-날짜-및-시간-데이터-처리" data-toc-modified-id="3.-날짜-및-시간-데이터-처리-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>3. 날짜 및 시간 데이터 처리</a></span></li></ul></li></ul></div>

### 제4절 함수 적용과 특수 데이터 처리
#### 2. 문자열 데이터 처리

In [1]:
# 예제 데이터 선언
import pandas as pd
import numpy as np

score = {
    '성별': ['여자', '남자', '여자', '남자', '남자'],
    '성적': [70, 80, 90, 50, 100],
    '가산점': [5, 10, 0, 10, 5]
}
score = pd.DataFrame(score)
score

   성별   성적  가산점
0  여자   70    5
1  남자   80   10
2  여자   90    0
3  남자   50   10
4  남자  100    5

In [2]:
score[['성적', '가산점']].apply(np.mean)

성적     78.0
가산점     6.0
dtype: float64

In [3]:
score_pivot = score.pivot_table(columns='성별', values='성적')
score_pivot.apply(np.mean, axis=0)

성별
남자    76.666667
여자    80.000000
dtype: float64

In [4]:
def final_score(row):
    total = row['성적'] + row['가산점']
    return min(total, 100)

score['최종점수'] = score.apply(final_score, axis=1)
score

   성별   성적  가산점  최종점수
0  여자   70    5    75
1  남자   80   10    90
2  여자   90    0    90
3  남자   50   10    60
4  남자  100    5   100

In [5]:
gender_map = {'남자': 'M', '여자': 'F'}
score['성별코드'] = score['성별'].map(gender_map)
score

   성별   성적  가산점  최종점수 성별코드
0  여자   70    5    75    F
1  남자   80   10    90    M
2  여자   90    0    90    F
3  남자   50   10    60    M
4  남자  100    5   100    M

In [6]:
score['합격여부'] = score['최종점수'].map(lambda x: '합격' if x >= 80 else '불합격')
score

   성별   성적  가산점  최종점수 성별코드 합격여부
0  여자   70    5    75    F  불합격
1  남자   80   10    90    M   합격
2  여자   90    0    90    F   합격
3  남자   50   10    60    M  불합격
4  남자  100    5   100    M   합격

In [7]:
import pandas as pd

landmark = pd.DataFrame({
    'name': ['경복궁', '불국사', '첨성대', '광한루원', '창경궁'],
    'english name': [
        'Gyeongbokgung Palace',
        'bulguksa',
        'cheomseongdae observatory',
        'gwanghanru',
        'Changgyeonggung Palace'
    ],
    'location': [
        '서울특별시 종로구 사직로 161',
        '경북 경주시 불국로 385',
        '경북 경주시 인왕동 839-1',
        '전북 남원시 요천로 1447',
        '서울 종로구 창경궁로 185'
    ]
})

In [8]:
landmark['name_upper'] = landmark['english name'].str.upper()
landmark['name_lower'] = landmark['english name'].str.lower()
landmark

,name,english name,location,name_upper,name_lower
0,경복궁,Gyeongbokgung Palace,서울특별시 종로구 사직로 161,GYEONGBOKGUNG PALACE,gyeongbokgung palace
1,불국사,bulguksa,경북 경주시 불국로 385,BULGUKSA,bulguksa
2,첨성대,cheomseongdae observatory,경북 경주시 인왕동 839-1,CHEOMSEONGDAE OBSERVATORY,cheomseongdae observatory
3,광한루원,gwanghanru,전북 남원시 요천로 1447,GWANGHANRU,gwanghanru
4,창경궁,Changgyeonggung Palace,서울 종로구 창경궁로 185,CHANGGYEONGGUNG PALACE,changgyeonggung palace

In [9]:
# 하나의 컬럼에 공백제거를 수행하는 방법
landmark['english name'] = landmark['english name'].str.strip()

# 모든 컬럼에 공백 제거를 수행하는 방법
for col in landmark.columns:
    landmark[col] = landmark[col].str.strip()

In [10]:
landmark['location'].str[3:6]

0    별시
1    경주시
2    경주시
3    남원시
4    종로구
Name: location, dtype: object

In [11]:
landmark['location'].str.split().str.get(1)

0    종로구
1    경주시
2    경주시
3    남원시
4    종로구
Name: location, dtype: object

In [12]:
landmark['name_replace'] = landmark['english name'].str.replace(' ', '_', regex=False)
landmark['simple'] = (
    landmark['location']
    .str.replace('서울특별시', '서울', regex=False)
    .str.replace('경북 경주시', '경주', regex=False)
    .str.replace('전북 남원시', '남원', regex=False)
)
landmark[['english name', 'name_replace', 'location', 'simple']]

,english name,name_replace,location,simple
0,Gyeongbokgung Palace,Gyeongbokgung_Palace,서울특별시 종로구 사직로 161,서울 종로구 사직로 161
1,bulguksa,bulguksa,경북 경주시 불국로 385,경주 불국로 385
2,cheomseongdae observatory,cheomseongdae_observatory,경북 경주시 인왕동 839-1,경주 인왕동 839-1
3,gwanghanru,gwanghanru,전북 남원시 요천로 1447,남원 요천로 1447
4,Changgyeonggung Palace,Changgyeonggung_Palace,서울 종로구 창경궁로 185,서울 종로구 창경궁로 185

In [13]:
landmark['location'].str.extract('(경주)')

     0
0  NaN
1   경주
2   경주
3  NaN
4  NaN

In [14]:
landmark['location'].str.extract(r'(\d+-?\d*)')

       0
0    161
1    385
2  839-1
3   1447
4    185

In [15]:
seoul = landmark[landmark['location'].str.contains('서울', regex=False)]
seoul

,name,english name,location,name_upper,name_lower,name_replace,simple
0,경복궁,Gyeongbokgung Palace,서울특별시 종로구 사직로 161,GYEONGBOKGUNG PALACE,gyeongbokgung palace,Gyeongbokgung_Palace,서울 종로구 사직로 161
4,창경궁,Changgyeonggung Palace,서울 종로구 창경궁로 185,CHANGGYEONGGUNG PALACE,changgyeonggung palace,Changgyeonggung_Palace,서울 종로구 창경궁로 185

In [16]:
landmark['region'] = landmark['location'].str.extract(r'^(서울|경북|전북)')
landmark['is_seoul'] = landmark['location'].str.contains('서울', regex=False)
landmark[['location', 'region', 'is_seoul']]

            location region  is_seoul
0  서울특별시 종로구 사직로 161     서울      True
1     경북 경주시 불국로 385     경북     False
2   경북 경주시 인왕동 839-1     경북     False
3    전북 남원시 요천로 1447     전북     False
4    서울 종로구 창경궁로 185     서울      True

In [17]:
landmark['address_number'] = (
    landmark['location']
    .str.extract(r'(\d+)')
    .astype(int)
)
landmark[['address_number', 'location']]

   address_number           location
0             161  서울특별시 종로구 사직로 161
1             385     경북 경주시 불국로 385
2             839   경북 경주시 인왕동 839-1
3            1447    전북 남원시 요천로 1447
4             185    서울 종로구 창경궁로 185

In [18]:
landmark['english name'].str.contains('Palace', regex=False)

0     True
1    False
2    False
3    False
4     True
Name: english name, dtype: bool

In [19]:
landmark['location'].str.startswith('서울')

0     True
1    False
2    False
3    False
4     True
Name: location, dtype: bool

In [20]:
landmark['location'].str.endswith('1')

0     True
1    False
2     True
3    False
4    False
Name: location, dtype: bool

In [21]:
import numpy as np
import pandas as pd

landmark = pd.DataFrame({
    'name': ['경복궁', '불국사', '첨성대', '광한루원', None],
    'english name': [
        'Gyeongbokgung Palace',
        None,
        'cheomseongdae observatory',
        'gwanghanru',
        'Changgyeonggung Palace'
    ],
    'location': [
        '서울특별시 종로구 사직로 161',
        '경북 경주시 불국로 385',
        '경북 경주시 인왕동 839-1',
        None,
        '서울 종로구 창경궁로 185'
    ]
})

landmark.loc[3, 'name'] = '삭제'
landmark.loc[2, 'location'] = '삭제'

landmark

   name               english name           location
0   경복궁       Gyeongbokgung Palace  서울특별시 종로구 사직로 161
1   불국사                       None     경북 경주시 불국로 385
2   첨성대  cheomseongdae observatory                 삭제
3    삭제                 gwanghanru               None
4  None     Changgyeonggung Palace    서울 종로구 창경궁로 185

In [22]:
landmark.isna()

    name  english name  location
0  False         False     False
1  False          True     False
2  False         False     False
3  False         False      True
4   True         False     False

In [23]:
# 'name' 컬럼에서 '삭제' 값을 포함한 행 제거
landmark[landmark['name'] != '삭제']

   name               english name           location
0   경복궁       Gyeongbokgung Palace  서울특별시 종로구 사직로 161
1   불국사                       None     경북 경주시 불국로 385
2   첨성대  cheomseongdae observatory                 삭제
4  None     Changgyeonggung Palace    서울 종로구 창경궁로 185

In [24]:
# 'english name' 컬럼에서 결측치(NaN) 행 제거
landmark.dropna(subset=['english name'])

   name               english name           location
0   경복궁       Gyeongbokgung Palace  서울특별시 종로구 사직로 161
2   첨성대  cheomseongdae observatory                 삭제
3    삭제                 gwanghanru               None
4  None     Changgyeonggung Palace    서울 종로구 창경궁로 185

In [25]:
# 'english name' 컬럼에서 결측치를 'unknown'으로 대체
landmark['english name'] = landmark['english name'].fillna('삭제')

# "삭제"와 같은 문자열을 None으로 대체
landmark['name'] = landmark['name'].replace('삭제', None)

landmark

   name               english name           location
0   경복궁       Gyeongbokgung Palace  서울특별시 종로구 사직로 161
1   불국사                         삭제     경북 경주시 불국로 385
2   첨성대  cheomseongdae observatory                 삭제
3   첨성대                 gwanghanru               None
4  None     Changgyeonggung Palace    서울 종로구 창경궁로 185

In [26]:
landmark['english name'].str.contains('Palace', na=False)

0     True
1    False
2    False
3    False
4     True
Name: english name, dtype: bool

#### 3. 날짜 및 시간 데이터 처리

In [27]:
from datetime import datetime

# 현재 날짜와 시간 출력
datetime.today()

datetime.datetime(2026, 3, 2, 16, 45, 35, 164257)

In [28]:
# 현재 연도만 추출
datetime.today().year

2026

In [29]:
datetime.strptime('2022-01-01 00:00:00', '%Y-%m-%d %H:%M:%S')

datetime.datetime(2022, 1, 1, 0, 0)

In [30]:
time = datetime.today()
time.strftime('%Y-%m-%d %H:%M:%S')

'2026-03-02 16:45:35'

In [31]:
from datetime import timedelta

# 현재 시간에 100일을 더한 날짜 계산
time = datetime.today()
time + timedelta(days=100)

datetime.datetime(2026, 6, 10, 16, 45, 35, 934050)