<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import numpy as np
import pandas as pd

dataset = np.array([['kor', 70], ['math', 80]])
df = pd.DataFrame(dataset, columns=['class', 'score'])
df

  class score
0   kor    70
1  math    80

In [2]:
df = pd.DataFrame([['kor', 70], ['math', 80]], columns=['class', 'score'])

In [3]:
df = pd.DataFrame({'class': ['kor', 'math'], 'score': [70, 80]})

In [4]:
filepath ='data.csv'
df.to_csv(filepath , encoding='utf-8')

In [5]:
df = pd.read_csv(filepath, na_values='Blank', encoding='utf-8')

In [6]:
from sklearn.datasets import load_iris
iris = load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)

In [7]:
iris

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [8]:
iris.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
iris.tail()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [10]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [11]:
iris.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [12]:
iris.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
dtype: object

In [13]:
iris['sepal length (cm)'] = iris['sepal length (cm)'].astype('int')
iris[['sepal width (cm)', 'petal length (cm)']] = \
iris[['sepal width (cm)', 'petal length (cm)']].astype('int')
iris.head(3)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5                 3                  1               0.2
1                  4                 3                  1               0.2
2                  4                 3                  1               0.2

In [14]:
iris.index

RangeIndex(start=0, stop=150, step=1)

In [15]:
iris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [16]:
iris.set_index('sepal length (cm)', drop =True, append =False, inplace =True)
iris.head()

                   sepal width (cm)  petal length (cm)  petal width (cm)
sepal length (cm)
5                                 3                  1               0.2
4                                 3                  1               0.2
4                                 3                  1               0.2
4                                 3                  1               0.2
5                                 3                  1               0.2

In [17]:
iris.reset_index(inplace=True)
iris.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5                 3                  1               0.2
1                  4                 3                  1               0.2
2                  4                 3                  1               0.2
3                  4                 3                  1               0.2
4                  5                 3                  1               0.2

In [18]:
iris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [19]:
iris.columns = [
    'Sepal Length', 'Sepa lWidth', 'Petal Length', 'Petal Width'
]
iris.columns

Index(['Sepal Length', 'Sepa lWidth', 'Petal Length', 'Petal Width'], dtype='object')

In [20]:
iris.columns = iris.columns.str.replace(' ', '_')
iris.head(3)

   Sepal_Length  Sepa_lWidth  Petal_Length  Petal_Width
0             5            3             1          0.2
1             4            3             1          0.2
2             4            3             1          0.2